-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.student
(
    student_id integer NOT NULL,
    name character varying(30) NOT NULL,
    email character varying(20) NOT NULL,
    "group" character varying(5) NOT NULL,
    CONSTRAINT student_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.supervisor
(
    supervisor_id integer NOT NULL,
    name character varying(30) NOT NULL,
    "department " character varying(30) NOT NULL,
    email character varying(30) NOT NULL,
    CONSTRAINT supervisor_pkey PRIMARY KEY (id),
    UNIQUE (supervisor_id)
);

CREATE TABLE IF NOT EXISTS public.project
(
    project_id integer NOT NULL,
    title character varying(30) NOT NULL,
    start_date date NOT NULL,
    supervisor_id integer,
    status character varying(10) NOT NULL,
    student_id integer,
    CONSTRAINT project_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.participation
(
    participation_id integer NOT NULL,
    student_id integer NOT NULL,
    " project_id " integer NOT NULL,
    assigned_at date NOT NULL,
    grade integer NOT NULL,
    CONSTRAINT participation_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.project
    ADD FOREIGN KEY (supervisor_id)
    REFERENCES public.supervisor (supervisor_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.project
    ADD FOREIGN KEY (student_id)
    REFERENCES public.student (student_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;